#!/bin/sh -v
#
# Audio import handler for xwax
#
# This script takes an output sample rate and filename as arguments,
# and outputs signed, little-endian, 16-bit, 2 channel audio on
# standard output. Errors to standard error.
#
# You can adjust this script yourself to customise the support for
# different file formats and codecs.
#

FILE="$1"
RATE="$2"

case "$FILE" in

*.cdaudio)
	echo "Calling CD extract..." >&2
	exec cdparanoia -r `cat "$FILE"` -
	;;

*.mp3)
	echo "Calling MP3 decoder..." >&2
	exec ffmpeg -loglevel verbose -hwaccel hw:0 -i "$FILE" -ar "$RATE"  -f s16le -c:a pcm_s16le -
	;;

*.wav)
	echo "Calling wav decoder..." >&2
	exec ffmpeg -loglevel verbose -hwaccel hw:0 -i "$FILE" -ar "$RATE" -f s16le -c:a pcm_s16le -
	;;
	
*.ogg)
	echo "Calling ogg decoder..." >&2
	ffmpeg -loglevel verbose -hwaccel hw:0 -acodec vorbis -i "$FILE" -ar "$RATE" -f s16le  -c:a pcm_s16le -
	;;
*)
	echo "Calling fallback decoder..." >&2

	FFMPEG=$(which ffmpeg 2> /dev/null || which avconv 2> /dev/null)

	if [ -z "$FFMPEG" ]; then
		echo "$0: no ffmpeg or avconv available to decode file" >&2
		exit 1
	fi

	exec "${FFMPEG}" -loglevel verbose -acodec vorbis -i "$FILE" -ar "$RATE" -f s16le -c:a pcm_s16le -
	;;

esac
